# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/jazzband/pip-tools
    rev: '6.12.0'
    hooks:
      - id: pip-compile
        # NB: Important to run pip-compile with same python version as
        # consumes the requirements.txt
        language_version: 'python3.10'
        args: [--resolver, backtracking, --quiet]
