name: Build and publish Lektor Website

on: push

jobs:
  deploy:
    uses: dairiki/lektor-ci/.github/workflows/build-and-deploy.yml@feat.all-in-one
    with:
      python-version: "3.10"
      environment: staging
    secrets:
      ssh-key: ${{ secrets.RSYNC_SSH_KEY }}
