name: Build and publish Lektor Website

on: push

jobs:
  build:
    uses: dairiki/lektor-ci/.github/workflows/build.yml@v1
    with:
      python-version: "3.10"

  deploy:
    needs: build
    uses: dairiki/lektor-ci/.github/workflows/deploy.yml@v1
    with:
      environment: staging
    secrets:
      ssh-key: ${{ secrets.RSYNC_SSH_KEY }}
